FROM node:22 AS build
## FIXME : This image contains vulnerability issues
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./

RUN npm install -g @angular/cli

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
