FROM node:22 AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./

RUN npm install -g @angular/cli
RUN npm i @geoman-io/leaflet-geoman-free

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
