# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run-dev:
    desc: "Run the development server"
    cmds:
      - echo "Starting the development server..."
      - npm run start
