services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./init-data.sql:/docker-entrypoint-initdb.d/init-data.sql

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    restart: always
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver/data_dir:/opt/geoserver/data_dir

  spring-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - postgis

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=${NODE_ENV}

volumes:
  postgis-data:
  geoserver-data:
