# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run-dev:
    desc: "Run the Spring Boot application"
    cmds:
      - echo "Starting the Spring Boot application..."
      - mvn spring-boot:run